### ISSUE TITLE
Cube2D: 2D Slice of a Cube

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/cube#29]
This is a proposal for a new object, ```Cube2D```.  This object is conceived as a generalized sunpy-compatible 2D data object for solar data which can be stand alone or, more importantly, be a 2D slice of a 3D or 4D ```Cube``` object.  An object like this will enable an objective of both sunpycube and IRISpy to be achieved simultaneously.
* A generalized plot function for any 2D slice of a ```Cube```, e.g. ```>>> Cube[0].plot()```, ```Cube[:,:,0].plot()``` or ```>>> CubeSequence[0,0].plot()```, ```>>> CubeSequence.index_as_cube[0].plot()```
* A ```CubeSequence``` can be populated with ```Cube2D``` objects instead of ```Cube``` objects.  Thus each exposure will have its own WCS object.  This enables manual fine pointing adjustments to be made on an exposure-by-exposure basis.  Meanwhile only small additions to ```CubeSequence``` methods like ```CubeSequence.animate()``` can be made based on an if statement checking whether the ```CubeSequence``` contains ```Cube``` or ```Cube2D``` objects.

A ```Cube2D``` object should be include:
* 2D array of data.  Must be unit aware, i.e. an astropy Quantity
* a ```sunpycube.wcs_util.WCS``` object of the two axes.  Can be any type of dimension, time, wavelength etc.  Should be able to take a single Lat or Lon axis, or be able to derive Lat and Lon from a single data axis.  Does the splittling of Lat and Lon axes in a WCS object already exist in ```sunpycube.cube.wcs_utils.WCS```?
* ```Cube2D.plot()```: plots the image automatically derives the axes from the WCS object.  Should have a kwarg like ```swap_axes=False``` or something similar which allows the user to plot y vs. x or x vs. y depending on whether kwarg is ```True``` or ```False```.  This should deprecate ```Cube.plot_wavelength_slice()``` and ```Cube.plot_x_slice()```.
* ```Cube2D.to_map()```: convert to sunpy map if dimensions are both spatial. This should deprecate ```Cube.slice_to_map()```
* ```Cube2D.to_spectrogram()```: convert to sunpy map if dimensions are one spatial, one spectral.  This should deprecate ```Cube.slice_to_spectrogram()```
* ```Cube2D.world_to_pix()```: similar to Map
* ```Cube2D.pix_to_world()```: similar to Map

**Comment by Cadair** [comment]
Common API over Cube and all sub-dimensional classes: 

* `pixel_to_world`, `world_to_pixel`
* `plot`
* `__getitem__` returns one of the Cube subclasses.
* `to_sunpy` used `.to_sunpy(sunpy.map.Map)`, or `.to_sunpy()`.
* `.dimensions` (returns quantity)

plus stuff inherited from NDData:

* `unit`
* `data`
* `meta`
* `uncertainty`
* `mask`
