### ISSUE TITLE
Generalize Cube to 1D-4D (Or Even ND)

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/cube#32]
This is a proposal for generalizing Cube to lower dimensions.  At the moment Cube is designed as a coupling of 3D and 4D data arrays with a corresponding wcs object.  This rewrite would allow it to represent 2D and 1D data as well, and possibly even higher dimensions.  The principle of this concept is to define a minimal common API and implementation for data of any dimension and any WCS axis types.  The current concept is that these ```Cube``` objects would then be subclassed or wrapped as part of other user facing objects.  Below is the hierarchy and API we thusfar believe is required.

# Hierarchy and API
## Cube - Parent class
```Cube(astropy.nddata.NDData)```: A parent class for 3D, 4D and possible high dimension Cubes.  It is conceived that this class would be subclassed to create Cube2D and Cube1D.  Cube is subclassed from ```astropy.nddata.NDData```
**API Inherited from ```astropy.nddata.NDData```**
* unit
* data
* meta
* uncertainty
* mask

**Cube-specific API**
* ```pixel_to_world```: similar to equivalent function in ```sunpy.map.Map``` to convert pixel coordinates to world coordinates using the ```wcs``` attribute.
* ```world_to_pixel```: similar to equivalent function in ```sunpy.map.Map``` to convert world coordinates to pixel coordinates using the ```wcs``` attribute.
* ```to_sunpy()```: Convert to relevant SunPy object based on dimensions, e.g. 2D Cube with two spatial dimensions would be converted to ```sunpy.map.Map```.  1D Cube with time axis would be converted to a ```sunpy.timeseries.TimeSeries```, etc.
* ```dimensions```: same as equivalent function in ```sunpy.map.Map```, i.e. returns a Quantity of number of pixels in each dimensions with ```u.pix``` as unit.
* ```plot```: produce a ```sunpy.imageanimator.ImageAnimatorWCS``` in the same way that current ```Cube.animate()``` does.
* ```__getitem__```: Slice returned would be either a ```Cube1D```,  ```Cube2D``` or a ```Cube``` depending on the dimensions of the slice.

All above API is common to all Cube subclasses.

## Cube1D
```Cube1D(Cube)```: A cube for 1D data subclassed from ```Cube```
**API**
* ```plot```: Overwrite ```Cube.plot``` to produce a 1D plot deriving y-axis from data values and x-axis from WCS object.
* ```__getitem__```: getitem may have to be specific to 1D data.  The slice would be another ```Cube1D``` or some single value object, e.g. ```float``` or ```Quantity``` depending on the dimension of the slice.

## Cube2D
```Cube2D(Cube)```: A cube for 2D data subclassed from ```Cube```
**API**
* ```plot```: produce a 2D plot of the data using WCS axes
* ```__getitem__```: getitem may have to be specific to 2D data.  The slice returned would be either a ```Cube1D``` or a ```Cube2D``` depending on the dimensions of the slice.

## Higher Dimensional Cubes
In principle ```Cube``` should be valid for >3D Cubes as well so long as there is a corresponding >3D wcs object.

# Implementation
This object could be implemented by removing most of the API from the current ```Cube``` implementation, generalizing the bits common between dimensions and moving them into the API structure described above.  Dimension-specific 1D and 2D subclasses could then be written by overwriting the ```plot``` method and possibly a ```__getitem__``` method if necessary.

Because the Cube subclasses are conceived to work as slices of higher dimensional Cubes, they will have to be able to appear to separate in separable WCS axes, e.g. latitude and longitude.  Infrastructure to do this already exists in ```sunpycube.cube.wcs_util```.

**Comment by MSKirk** [comment]
Under Cube 1D, maybe have a `to_dataframe` to dump information into a pandas environment.

**Comment by DanRyanIrish** [comment]
I think that would be achieved by converting to a TimeSeries via ```to_sunpy()``` and getting at a ```pandas.DataFrame``` from there.  The idea is to have a minimalist approach such that all subclasses have the same API.

But there would be nothing from stopping someone from subclassing ```Cube1D``` and adding that method themselves for their own work or for an instrument-specific class.

**Comment by Cadair** [comment]
I don't think we need Cube3D as the plot will just be a call to ImageAnimatorWCS like the base cube. Also shape should be dimensions a-la map.

**Comment by DanRyanIrish** [comment]
I've adjusted the description above accordingly.
